name: nfc_manager
description: A Flutter plugin providing access to NFC features on Android and iOS.
repository: https://github.com/okadan/flutter-nfc-manager
version: 4.1.1

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  ndef_record: ^1.3.3

dev_dependencies:
  flutter_lints: ^5.0.0
  pigeon: ^26.0.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutter.plugins.nfcmanager
        pluginClass: NfcManagerPlugin
      ios:
        pluginClass: NfcManagerPlugin
