name: nfc_manager
description: Flutter plugin for accessing the NFC features on Android and iOS.
version: 3.2.0
homepage: https://github.com/okadan/flutter-nfc-manager

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.nfcmanager
        pluginClass: NfcManagerPlugin
      ios:
        pluginClass: NfcManagerPlugin
